# Generated by Django 2.2.6 on 2022-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ElementData',
        ),
    ]
