# Generated by Django 2.2.6 on 2022-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
