# Generated by Django 2.2.6 on 2022-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220215_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='children',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
