# Generated by Django 2.2.6 on 2022-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220215_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='children',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
