# Generated by Django 2.2.6 on 2022-02-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220215_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
