# Generated by Django 2.2.6 on 2022-03-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220216_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Element'),
        ),
    ]
